### ISSUE TITLE
Data never loads - new user

### ISSUE THREAD

**Issue by p3sulli** [HanSolo/Gluco-Tracker#10] opened 2020-10-15 02:01 UTC
I have been using nightscout for years and all the other apps that use the same nightscout URL method work except this one. No errors - just nothing ever loads - running the current night scout versions

**Comment by HanSolo** [comment] 2020-10-15 03:38
Hi there, if possible please send me your nightscout url so that I can debug. You can send it to: han dot solo dot gg at gmail dot com
Often the problem is coming from variables I’m not aware of or formats used in the protocol. Until now I got all versions running but like I wrote I would need either the nightscout url or the json output itself.

**Comment by HanSolo** [comment] 2020-10-19 05:22
Will close this one because of the lack of information. If you take the time to file an issue please do the extra step and provide some info on how to reproduce the problem. A report like this is unfortunately totally useless...just say‘n

**Closed** 2020-10-19 05:23 UTC
